In [1]:
import numpy as np

# Define the input feature map
input_feature_map = np.array([
    [3, 5, 2, 8, 1],
    [9, 7, 5, 4, 3],
    [2, 0, 6, 1, 6],
    [6, 3, 7, 9, 2],
    [1, 4, 9, 5, 1]
])

# Define the filter
filter_matrix = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1]
])

# Define the size of the filter and input feature map
filter_size = filter_matrix.shape[0]
input_size = input_feature_map.shape[0]

# Define the size of the output feature map
output_size = input_size - filter_size + 1

# Initialize the output feature map
output_feature_map = np.zeros((output_size, output_size))

# Perform the convolution operation
for i in range(output_size):
    for j in range(output_size):
        output_feature_map[i, j] = np.sum(input_feature_map[i:i+filter_size, j:j+filter_size] * filter_matrix)

# Print the output feature map
print("Output Feature Map:")
print(output_feature_map)

Output Feature Map:
[[25. 18. 17.]
 [18. 22. 14.]
 [20. 15. 23.]]
